export const TILE_SIZE = 16;

export const CANVAS_WIDTH = 960;
export const CANVAS_HEIGHT = 540;

export const PLAYER_SIZE = 14;

export const BULLET_ANIM_SPEED = 0.15;

export const WEAPONS = {
  pistol: {
    id: 'pistol',
    name: 'Pistola',
    fireRate: 18,
    damage: 2,
    bulletSpeed: 16,
    spread: 0.08,
    bulletsPerShot: 1,
    ammo: 36,
    magSize: 12,
    reloadTime: 30,
    icon: '🔫',
  },
  revolver: {
    id: 'revolver',
    name: 'Revólver',
    fireRate: 35,
    damage: 4,
    bulletSpeed: 18,
    spread: 0.04,
    bulletsPerShot: 1,
    ammo: 24,
    magSize: 6,
    reloadTime: 40,
    icon: '🔫',
  },
  smg: {
    id: 'smg',
    name: 'Subfusil',
    fireRate: 12,
    damage: 1,
    bulletSpeed: 16,
    spread: 0.14,
    bulletsPerShot: 1,
    ammo: 90,
    magSize: 30,
    reloadTime: 35,
    icon: '🔫',
  },
  wand: {
    id: 'wand',
    name: 'Báculo Mágico',
    fireRate: 22,
    damage: 3,
    bulletSpeed: 17,
    spread: 0.03,
    bulletsPerShot: 1,
    ammo: 45,
    magSize: 15,
    reloadTime: 25,
    icon: '🔮',
  },
  rifle: {
    id: 'rifle',
    name: 'Rifle',
    fireRate: 25,
    damage: 3,
    bulletSpeed: 20,
    spread: 0.02,
    bulletsPerShot: 1,
    ammo: 30,
    magSize: 10,
    reloadTime: 40,
    icon: '🔫',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Escopeta',
    fireRate: 45,
    damage: 1,
    bulletSpeed: 14,
    spread: 0.25,
    bulletsPerShot: 5,
    ammo: 18,
    magSize: 6,
    reloadTime: 50,
    icon: '💥',
  },
  crossbow: {
    id: 'crossbow',
    name: 'Ballesta',
    fireRate: 48,
    damage: 6,
    bulletSpeed: 18,
    spread: 0.01,
    bulletsPerShot: 1,
    ammo: 12,
    magSize: 1,
    reloadTime: 35,
    icon: '🏹',
  },
  sniper: {
    id: 'sniper',
    name: 'Francotirador',
    fireRate: 65,
    damage: 8,
    bulletSpeed: 24,
    spread: 0.01,
    bulletsPerShot: 1,
    ammo: 15,
    magSize: 5,
    reloadTime: 55,
    icon: '🎯',
  },
  uzi: {
    id: 'uzi',
    name: 'UZI',
    fireRate: 10,
    damage: 1,
    bulletSpeed: 15,
    spread: 0.18,
    bulletsPerShot: 1,
    ammo: 105,
    magSize: 35,
    reloadTime: 30,
    icon: '⚡',
  },
  rpg: {
    id: 'rpg',
    name: 'Lanzacohetes',
    fireRate: 70,
    damage: 5,
    bulletSpeed: 8,
    spread: 0.03,
    bulletsPerShot: 1,
    ammo: 5,
    magSize: 1,
    reloadTime: 70,
    icon: '🚀',
    explosive: true,
  },
  minigun: {
    id: 'minigun',
    name: 'Minigun',
    fireRate: 10,
    damage: 1,
    bulletSpeed: 16,
    spread: 0.18,
    bulletsPerShot: 1,
    ammo: 180,
    magSize: 60,
    reloadTime: 60,
    icon: '💀',
  },
  raygun: {
    id: 'raygun',
    name: 'Rayo Láser',
    fireRate: 18,
    damage: 3,
    bulletSpeed: 22,
    spread: 0.02,
    bulletsPerShot: 1,
    ammo: 60,
    magSize: 20,
    reloadTime: 30,
    icon: '⚡',
    pierce: 1,
  },
  grenade_launcher: {
    id: 'grenade_launcher',
    name: 'Lanzagranadas',
    fireRate: 50,
    damage: 4,
    bulletSpeed: 9,
    spread: 0.06,
    bulletsPerShot: 1,
    ammo: 6,
    magSize: 1,
    reloadTime: 55,
    icon: '💣',
    explosive: true,
  },
};

export const UPGRADE_POOL = [
  { id: 'hp_plus', name: '+1 Vida', desc: 'Aumenta tu vida máxima en 1', icon: '❤', maxStack: 5, prereq: null },
  { id: 'weapon_damage', name: 'Daño +1', desc: 'Tus disparos hacen +1 de daño', icon: '⬆', maxStack: 5, prereq: null },
  { id: 'fire_rate', name: 'Cadencia +10%', desc: 'Disparas un 10% más rápido', icon: '⚡', maxStack: 3, prereq: null },
  { id: 'pierce', name: 'Perforación', desc: 'Tus balas atraviesan 1 enemigo', icon: '→', maxStack: 2, prereq: 'weapon_damage' },
  { id: 'explosive', name: 'Impactos Explosivos', desc: 'Tus balas explotan al impactar', icon: '💥', maxStack: 1, prereq: 'pierce' },
  { id: 'knife', name: 'Cuchillo', desc: 'Desbloquea ataque cuerpo a cuerpo (F)', icon: '🗡', maxStack: 1, prereq: null },
  { id: 'knife_damage', name: 'Cuchillo +Daño', desc: 'El cuchillo hace +1 de daño', icon: '🗡', maxStack: 3, prereq: 'knife' },
  { id: 'knife_range', name: 'Cuchillo +Alcance', desc: 'Aumenta el alcance del cuchillo +8px', icon: '📏', maxStack: 2, prereq: 'knife' },
  { id: 'speed_boots', name: 'Botas Veloces', desc: '+15% velocidad de movimiento', icon: '👟', maxStack: 3, prereq: null },
  { id: 'ammo_up', name: 'Munición +25%', desc: 'Aumenta la munición máxima un 25%', icon: '📦', maxStack: 3, prereq: null },
  { id: 'spread_down', name: 'Precisión +10%', desc: 'Reducen la dispersión un 10%', icon: '🎯', maxStack: 3, prereq: 'fire_rate' },
  { id: 'lifesteal', name: 'Robo de Vida', desc: 'Cura 1 HP cada 3 impactos', icon: '💉', maxStack: 2, prereq: 'weapon_damage' },
  { id: 'shield', name: 'Escudo', desc: 'Probabilidad del 20% de bloquear daño', icon: '🛡', maxStack: 2, prereq: null },
  { id: 'heal_on_kill', name: 'Sanación Letal', desc: 'Cura 1 HP al matar enemigos', icon: '💚', maxStack: 2, prereq: null },
  { id: 'bullet_size', name: 'Balas Grandes', desc: 'Aumenta el tamaño de proyectiles', icon: '🔵', maxStack: 2, prereq: 'weapon_damage' },
  { id: 'thorns', name: 'Espinas', desc: 'Refleja 1 de daño al recibir golpe', icon: '🌵', maxStack: 2, prereq: 'shield' },
  { id: 'coin_magnet', name: 'Imán de Monedas', desc: 'Atrae monedas desde más lejos', icon: '🧲', maxStack: 2, prereq: null },
  { id: 'regen', name: 'Regeneración', desc: 'Recupera 1 HP cada 5 seg', icon: '💖', maxStack: 3, prereq: null },
  { id: 'crit', name: 'Golpe Crítico', desc: '+10% de probabilidad de daño doble', icon: '🎯', maxStack: 3, prereq: 'weapon_damage' },
  { id: 'dodge', name: 'Evasión', desc: '+10% de probabilidad de esquivar ataques', icon: '💨', maxStack: 2, prereq: 'speed_boots' },
  { id: 'pet_damage', name: 'Mascota +Daño', desc: 'Tus mascotas hacen +1 de daño', icon: '🐾', maxStack: 3, prereq: null },
  { id: 'pet_hp', name: 'Mascota +Vida', desc: 'Tus mascotas ganan +3 HP máx', icon: '❤', maxStack: 3, prereq: null },
  { id: 'pet_speed', name: 'Mascota +Velocidad', desc: 'Velocidad de mascotas +12%', icon: '💨', maxStack: 2, prereq: null },
  { id: 'pet_attack', name: 'Mascota +Cadencia', desc: 'Ataque de mascotas +15%', icon: '⚔', maxStack: 2, prereq: null },
  { id: 'pet_respawn', name: 'Mascota +Respawn', desc: 'Reviven 25% más rápido', icon: '⏳', maxStack: 2, prereq: null },
  { id: 'ricochet', name: 'Rebote', desc: 'Tus balas rebotan 1 vez en paredes', icon: '🔄', maxStack: 1, prereq: 'pierce' },
  { id: 'slow_aura', name: 'Aura Gélida', desc: 'Enemigos cerca se mueven 20% más lento', icon: '❄', maxStack: 2, prereq: null },
  { id: 'greed', name: 'Codicia', desc: 'Los enemigos sueltan +1 moneda', icon: '💰', maxStack: 3, prereq: null },
  { id: 'adrenaline', name: 'Adrenalina', desc: '+20% velocidad con menos de 50% HP', icon: '💉', maxStack: 2, prereq: 'speed_boots' },
  { id: 'vengeance', name: 'Venganza', desc: 'Al recibir daño, devuelves 1 al atacante', icon: '⚡', maxStack: 2, prereq: 'thorns' },
  { id: 'last_stand', name: 'Último Aliento', desc: 'Una vez por piso, sobrevives con 1 HP', icon: '🛡', maxStack: 1, prereq: 'shield' },
];

export const DUNGEONS = [
  {
    id: 'catacombs',
    name: 'Cripta del Lamento Eterno',
    floors: 15,
    theme: 'undead',
    palette: ['#3a3a3a', '#5a4a3a', '#7a6a4a', '#2a2a2a', '#1a1a1a'],
    floorColor: '#4a4a3a',
    wallColor: '#2a2a2a',
    accentColor: '#6a8a5a',
    bossName: 'Rey Osario',
    unlocked: true,
    difficulty: 1,
    coinMultiplier: 1,
  },
  {
    id: 'forest',
    name: 'Fronda Abisal',
    floors: 12,
    theme: 'nature',
    palette: ['#2a4a2a', '#3a5a3a', '#4a7a3a', '#5a4a2a', '#2a3a1a'],
    floorColor: '#3a4a2a',
    wallColor: '#2a3a1a',
    accentColor: '#5a8a3a',
    bossName: 'Raíz Primigenia',
    unlocked: false,
    difficulty: 1.2,
    coinMultiplier: 1.2,
  },
  {
    id: 'inferno',
    name: 'Vórtice Ígneo',
    floors: 10,
    theme: 'fire',
    palette: ['#4a1a1a', '#6a2a1a', '#8a3a1a', '#aa4a1a', '#2a0a0a'],
    floorColor: '#5a2a1a',
    wallColor: '#2a0a0a',
    accentColor: '#aa4a1a',
    bossName: 'Salamandrarca',
    unlocked: false,
    difficulty: 1.5,
    coinMultiplier: 1.5,
  },
  {
    id: 'frost',
    name: 'Mortaja Helada',
    floors: 10,
    theme: 'ice',
    palette: ['#2a3a4a', '#3a5a6a', '#4a7a8a', '#6aaaba', '#1a2a3a'],
    floorColor: '#3a4a5a',
    wallColor: '#1a2a3a',
    accentColor: '#6aaaba',
    bossName: 'Corazón de Escarcha',
    unlocked: false,
    difficulty: 1.5,
    coinMultiplier: 1.5,
  },
  {
    id: 'void',
    name: 'Nexo Vacuo',
    floors: 15,
    theme: 'void',
    palette: ['#2a1a3a', '#3a1a5a', '#5a2a7a', '#7a3a9a', '#1a0a2a'],
    floorColor: '#3a1a4a',
    wallColor: '#1a0a2a',
    accentColor: '#7a3a9a',
    bossName: 'Astaroth, el Devorador',
    unlocked: false,
    difficulty: 2.0,
    coinMultiplier: 2.0,
  },
];

export const CHARACTERS = [
  {
    id: 'adventurer',
    name: 'Aventurero',
    desc: 'Versátil y equilibrado. Empieza con pistola.',
    hp: 5,
    speed: 2.0,
    weaponId: 'pistol',
    special: null,
    cost: 0,
    color: '#c8a060',
  },
  {
    id: 'knight',
    name: 'Caballero',
    desc: 'Resistente. Revólver de alto calibre y cuchillo inicial.',
    hp: 8,
    speed: 2.0,
    weaponId: 'revolver',
    special: 'knife_unlocked',
    cost: 100,
    color: '#6080c0',
  },
  {
    id: 'ninja',
    name: 'Mafioso',
    desc: 'Rápido y letal. Subfusil de disparo rápido.',
    hp: 3,
    speed: 2.5,
    weaponId: 'smg',
    special: 'stealth',
    cost: 250,
    color: '#404040',
  },
  {
    id: 'mage',
    name: 'Mago',
    desc: 'Frágil pero con báculo mágico que perfora enemigos.',
    hp: 4,
    speed: 2.0,
    weaponId: 'wand',
    special: 'pierce_basic',
    cost: 400,
    color: '#8040c0',
  },
  {
    id: 'ranger',
    name: 'Guardabosques',
    desc: 'Rifle de precisión. Alcance y daño superiores.',
    hp: 5,
    speed: 2.5,
    weaponId: 'rifle',
    special: 'long_shot',
    cost: 300,
    color: '#40a060',
  },
];

export const FLOOR_WEAPONS = ['shotgun', 'crossbow', 'sniper', 'uzi', 'rpg', 'minigun', 'raygun', 'grenade_launcher'];

export const PET_TEMPLATES = {
  dog: {
    id: 'dog',
    name: 'Perro',
    icon: '🐕',
    hp: 10,
    damage: 2,
    speed: 1.5,
    size: 10,
    attackRange: 22,
    attackRate: 25,
    petType: 'melee',
    followRadius: 70,
    respawnTime: 480,
    color: '#c8a060',
    cost: 0,
  },
  cat: {
    id: 'cat',
    name: 'Gato',
    icon: '🐈',
    hp: 8,
    damage: 1,
    speed: 2.2,
    size: 7,
    attackRange: 18,
    attackRate: 15,
    petType: 'melee',
    followRadius: 90,
    respawnTime: 360,
    color: '#6a6a6a',
    cost: 100,
  },
  crow: {
    id: 'crow',
    name: 'Cuervo',
    icon: '🐦',
    hp: 9,
    damage: 1,
    speed: 2.5,
    size: 8,
    attackRange: 60,
    attackRate: 40,
    petType: 'ranged',
    followRadius: 100,
    respawnTime: 540,
    color: '#2a2a2a',
    cost: 150,
  },
  wolf: {
    id: 'wolf',
    name: 'Lobo',
    icon: '🐺',
    hp: 15,
    damage: 3,
    speed: 1.8,
    size: 12,
    attackRange: 24,
    attackRate: 30,
    petType: 'melee',
    followRadius: 60,
    respawnTime: 600,
    color: '#5a5a6a',
    cost: 200,
  },
  dragon: {
    id: 'dragon',
    name: 'Dragón',
    icon: '🐉',
    hp: 20,
    damage: 4,
    speed: 1.2,
    size: 14,
    attackRange: 70,
    attackRate: 35,
    petType: 'ranged',
    followRadius: 50,
    respawnTime: 720,
    color: '#8a2a2a',
    cost: 500,
  },
  fox: {
    id: 'fox',
    name: 'Zorro',
    icon: '🦊',
    hp: 8,
    damage: 2,
    speed: 2.0,
    size: 9,
    attackRange: 20,
    attackRate: 20,
    petType: 'melee',
    followRadius: 80,
    respawnTime: 420,
    color: '#d86a2a',
    cost: 250,
  },
  owl: {
    id: 'owl',
    name: 'Búho',
    icon: '🦉',
    hp: 10,
    damage: 2,
    speed: 1.6,
    size: 9,
    attackRange: 80,
    attackRate: 45,
    petType: 'ranged',
    followRadius: 110,
    respawnTime: 480,
    color: '#6a5a4a',
    cost: 300,
  },
  bear: {
    id: 'bear',
    name: 'Oso',
    icon: '🐻',
    hp: 25,
    damage: 4,
    speed: 0.9,
    size: 14,
    attackRange: 24,
    attackRate: 40,
    petType: 'melee',
    followRadius: 50,
    respawnTime: 660,
    color: '#6a4a2a',
    cost: 400,
  },
  rabbit: {
    id: 'rabbit',
    name: 'Conejo',
    icon: '🐇',
    hp: 6,
    damage: 1,
    speed: 3.0,
    size: 6,
    attackRange: 16,
    attackRate: 12,
    petType: 'melee',
    followRadius: 100,
    respawnTime: 300,
    color: '#c0a080',
    cost: 120,
  },
  snake: {
    id: 'snake',
    name: 'Serpiente',
    icon: '🐍',
    hp: 8,
    damage: 2,
    speed: 2.0,
    size: 8,
    attackRange: 20,
    attackRate: 18,
    petType: 'melee',
    followRadius: 80,
    respawnTime: 420,
    color: '#4a8a4a',
    cost: 220,
  },
  tiger: {
    id: 'tiger',
    name: 'Tigre',
    icon: '🐯',
    hp: 18,
    damage: 4,
    speed: 2.2,
    size: 13,
    attackRange: 24,
    attackRate: 28,
    petType: 'melee',
    followRadius: 60,
    respawnTime: 540,
    color: '#d86a20',
    cost: 450,
  },
  phoenix: {
    id: 'phoenix',
    name: 'Fénix',
    icon: '🔥',
    hp: 14,
    damage: 3,
    speed: 1.8,
    size: 11,
    attackRange: 85,
    attackRate: 38,
    petType: 'ranged',
    followRadius: 90,
    respawnTime: 600,
    color: '#e04020',
    cost: 600,
  },
};

export const PET_SYNERGIES = [
  {
    ids: ['dog', 'wolf'],
    name: 'Manada',
    desc: 'Ambos hacen +1 de daño',
    icon: '🐕🐺',
    bonus: { type: 'damage', value: 1 },
  },
  {
    ids: ['cat', 'owl'],
    name: 'Cazadores Nocturnos',
    desc: 'Rango de detección +25%',
    icon: '🐈🦉',
    bonus: { type: 'detection', value: 0.25 },
  },
  {
    ids: ['dragon', 'phoenix'],
    name: 'Alas de Fuego',
    desc: 'Golpear enemigos inflige +1 de daño de quemadura',
    icon: '🐉🔥',
    bonus: { type: 'burn', value: 1 },
  },
  {
    ids: ['rabbit', 'fox'],
    name: 'Astucia',
    desc: 'Velocidad de movimiento +15%',
    icon: '🐇🦊',
    bonus: { type: 'speed', value: 0.15 },
  },
  {
    ids: ['snake', 'tiger'],
    name: 'Emboscada',
    desc: 'Primer golpe de mascota hace +2 de daño',
    icon: '🐍🐯',
    bonus: { type: 'ambush', value: 2 },
  },
  {
    ids: ['bear', 'dragon'],
    name: 'Colosos',
    desc: '+3 HP máximo para ambas mascotas',
    icon: '🐻🐉',
    bonus: { type: 'pet_hp', value: 3 },
  },
  {
    ids: ['crow', 'phoenix'],
    name: 'Renacer',
    desc: 'Mascotas reviven 25% más rápido',
    icon: '🐦🔥',
    bonus: { type: 'respawn', value: 0.25 },
  },
  {
    ids: ['dog', 'cat'],
    name: 'Mascotas Domésticas',
    desc: '+2 HP máximo para ambas',
    icon: '🐕🐈',
    bonus: { type: 'pet_hp', value: 2 },
  },
  {
    ids: ['wolf', 'tiger'],
    name: 'Fieras',
    desc: 'Velocidad de ataque +20%',
    icon: '🐺🐯',
    bonus: { type: 'attack_speed', value: 0.2 },
  },
  {
    ids: ['owl', 'snake'],
    name: 'Sigilo',
    desc: 'Los enemigos te detectan desde 15% más lejos',
    icon: '🦉🐍',
    bonus: { type: 'detection', value: 0.15 },
  },
];

export const GAME_STATES = {
  MENU: 'menu',
  CHARACTER_SELECT: 'char_select',
  DUNGEON_SELECT: 'dungeon_select',
  PLAYING: 'playing',
  UPGRADE: 'upgrade',
  PAUSED: 'paused',
  GAME_OVER: 'game_over',
  VICTORY: 'victory',
};
